import type { NextPage } from 'next'
import Head from 'next/head'
import Button from '../src/component/atoms/Button'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>모두의 리스트</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
        <Button>test</Button>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
